# Generated by Django 5.2.1 on 2025-11-14 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Timestamp automático de creación', verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, help_text='Timestamp automático de ultima modificación', verbose_name='Fecha de Modificación')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del proyecto', max_length=255, verbose_name='Nombre del Proyecto')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del proyecto', null=True, verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('planificado', 'Planificado'), ('en_curso', 'En Curso'), ('completado', 'Completado'), ('en_espera', 'En Espera'), ('cancelado', 'Cancelado')], default='planificado', help_text='Estado actual del proyecto', max_length=20, verbose_name='Estado')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin_estimada', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin Estimada')),
                ('tiempo_estimado_general', models.CharField(blank=True, help_text='Tiempo total estimado (ej: 40 horas)', max_length=100, null=True, verbose_name='Tiempo Estimado General')),
                ('usuario', models.ForeignKey(help_text='Usuario propietario de este recurso', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['usuario', 'fecha_fin_estimada', 'nombre'],
                'indexes': [models.Index(fields=['usuario', 'estado'], name='projects_pr_usuario_53d48d_idx'), models.Index(fields=['fecha_fin_estimada'], name='projects_pr_fecha_f_d9678b_idx')],
            },
        ),
    ]
