# Generated by Django 5.2.1 on 2025-11-16 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Timestamp automático de creación', verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, help_text='Timestamp automático de ultima modificación', verbose_name='Fecha de Modificación')),
                ('titulo', models.CharField(help_text='Título descriptivo de la tarea', max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada de la tarea', null=True, verbose_name='Descripción')),
                ('completada', models.BooleanField(default=False, help_text='Indica si la tarea está completada', verbose_name='Completada')),
                ('tiempo_estimado', models.DurationField(blank=True, help_text='Tiempo estimado para completar la tarea (ej. 2h30m)', null=True, verbose_name='Tiempo estimado')),
                ('fecha_asignada', models.DateField(blank=True, help_text='Dia en que se planea realizar la tarea', null=True, verbose_name='Fecha Asignada')),
                ('proyecto', models.ForeignKey(blank=True, help_text='Proyecto al que pertenece esta tarea (Opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='projects.proyecto', verbose_name='Proyecto')),
                ('usuario', models.ForeignKey(help_text='Usuario propietario de este recurso', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['usuario', 'fecha_asignada', 'titulo'],
                'indexes': [models.Index(fields=['usuario', 'completada'], name='tasks_tarea_usuario_3fd772_idx'), models.Index(fields=['usuario', 'fecha_asignada'], name='tasks_tarea_usuario_4143ec_idx'), models.Index(fields=['proyecto', 'completada'], name='tasks_tarea_proyect_b3d79a_idx')],
            },
        ),
    ]
