# Generated by Django 5.2.1 on 2025-05-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('completada', models.BooleanField(default=False)),
                ('tiempo_estimado', models.DurationField(blank=True, help_text='Tiempo estimado para completar la tarea (ej. 2h30m)', null=True)),
                ('fecha_asignada', models.DateField(blank=True, help_text='Día en que se planea realizar la tarea', null=True)),
            ],
            options={
                'ordering': ['fecha_asignada', 'titulo'],
            },
        ),
    ]
