# Generated by Django 5.2.1 on 2025-05-23 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_alter_tarea_options_tarea_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Proyecto')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción del Proyecto')),
                ('tiempo_estimado_general', models.CharField(blank=True, help_text='Ej: 1 semana, 2 meses, corto plazo', max_length=100, null=True, verbose_name='Tiempo Estimado General')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin_estimada', models.DateField(blank=True, null=True, verbose_name='Fecha de Finalización Estimada')),
                ('estado', models.CharField(choices=[('planificado', 'Planificado'), ('en_curso', 'En Curso'), ('completado', 'Completado'), ('en_espera', 'En Espera'), ('cancelado', 'Cancelado')], default='planificado', max_length=20, verbose_name='Estado del Proyecto')),
                ('fecha_creacion_proyecto', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['usuario', 'fecha_fin_estimada', 'nombre'],
            },
        ),
    ]
