# Generated by Django 5.2.1 on 2025-10-12 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='proyecto',
            field=models.ForeignKey(blank=True, help_text='Proyecto al que pertenece esta tarea (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='tareas.proyecto', verbose_name='Proyecto'),
        ),
    ]
