# Generated by Django 5.2.1 on 2025-10-16 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0004_tarea_proyecto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Titulo breve y descriptivo de la notificación', max_length=200, verbose_name='Titulo')),
                ('mensaje', models.TextField(help_text='Contenido detallado de la notificación', verbose_name='Mensaje')),
                ('tipo', models.CharField(choices=[('task', 'Tarea'), ('project', 'Proyecto'), ('system', 'Sistema'), ('achievement', 'Logro')], max_length=20, verbose_name='Tipo de Notificación')),
                ('subtipo', models.CharField(choices=[('critical', 'Crítico'), ('warning', 'Advertencia'), ('info', 'Información'), ('success', 'Éxito')], max_length=20, verbose_name='Nivel de Urgencia')),
                ('leida', models.BooleanField(default=False, help_text='Usuario ya vio la notificación', verbose_name='Leída')),
                ('accionada', models.BooleanField(default=False, help_text='Usuario ya actuo sobre la notificación', verbose_name='Accionada')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_vencimiento', models.DateTimeField(blank=True, help_text='Cuando caduca la relevancia de esta notificación', null=True, verbose_name='Fecha de Vencimiento')),
                ('business_context', models.JSONField(blank=True, help_text='Datos adicionales del analisis que generó esta notificación', null=True, verbose_name='Contexto de Business Logic')),
                ('proyecto_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tareas.proyecto', verbose_name='Proyecto Relacionado')),
                ('tarea_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tareas.tarea', verbose_name='Tarea Relacionada')),
                ('usuario', models.ForeignKey(help_text='Usuario que recibe la notificación', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['usuario', 'leida'], name='tareas_noti_usuario_be1d5e_idx'), models.Index(fields=['usuario', 'tipo', 'subtipo'], name='tareas_noti_usuario_313f0b_idx'), models.Index(fields=['fecha_creacion'], name='tareas_noti_fecha_c_d3714e_idx')],
            },
        ),
    ]
