# Generated by Django 5.2.1 on 2025-11-17 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Timestamp automático de creación', verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, help_text='Timestamp automático de ultima modificación', verbose_name='Fecha de Modificación')),
                ('titulo', models.CharField(help_text='Titulo breve de la notificacion', max_length=200, verbose_name='Titulo')),
                ('mensaje', models.TextField(help_text='Contenido detallado de la notificacion', verbose_name='Mensaje')),
                ('tipo', models.CharField(choices=[('task', 'Tarea'), ('project', 'Proyecto'), ('system', 'Sistema'), ('achievement', 'Logro')], help_text='Categoria de la notificacion', max_length=20, verbose_name='Tipo')),
                ('subtipo', models.CharField(choices=[('critical', 'Crítico'), ('warning', 'Advertencia'), ('info', 'Información'), ('success', 'Éxito')], help_text='Nivel de urgencia o importancia', max_length=20, verbose_name='Subtipo')),
                ('leida', models.BooleanField(default=False, help_text='Indica si el usuario ha leido la notificacion', verbose_name='Leida')),
                ('accionada', models.BooleanField(default=False, help_text='Indica si el usuario ha tomado acción sobre la notificacion', verbose_name='Accionada')),
                ('fecha_vencimiento', models.DateTimeField(blank=True, help_text='Fecha en que la notificación expira', null=True, verbose_name='Fecha de Vencimiento')),
                ('business_context', models.JSONField(blank=True, help_text='Datos adicionales en formato JSON', null=True, verbose_name='Contexto de Negocio')),
                ('proyecto_relacionado', models.ForeignKey(blank=True, help_text='Proyecto asociado a esta notificación', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='projects.proyecto', verbose_name='Proyecto Relacionado')),
                ('tarea_relacionada', models.ForeignKey(blank=True, help_text='Tarea asociada a esta notificación', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='tasks.tarea', verbose_name='Tarea Relacionada')),
                ('usuario', models.ForeignKey(help_text='Usuario propietario de este recurso', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['usuario', 'leida'], name='notificatio_usuario_8fe80f_idx'), models.Index(fields=['usuario', 'tipo', 'subtipo'], name='notificatio_usuario_b165ad_idx'), models.Index(fields=['fecha_creacion'], name='notificatio_fecha_c_929fc4_idx'), models.Index(fields=['tarea_relacionada'], name='notificatio_tarea_r_bbbc83_idx'), models.Index(fields=['proyecto_relacionado'], name='notificatio_proyect_09c218_idx')],
            },
        ),
    ]
